[mypy]
python_version = 3.12
disallow_untyped_defs = true
check_untyped_defs = true
# NOTE: does not actually work with pre-commit, since it supplies
#   changed files to mypy directly:
exclude = ^docs/

[mypy-*.tests.*]
disallow_untyped_defs = false

[mypy-docs.utils.*]
disallow_untyped_defs = false
