repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      #- id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.19
    hooks:
      - id: uv-lock

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        # NOTE: `exclude` is extracted from config file, see the note in the file
        exclude: "^docs/source/conf\\.py$"
        args:
          - "--config-file=.mypy-precommit.ini"
        additional_dependencies:
          - "pytest ~=9.0"
          - "sphinx ~=9.0"
          - "types-docutils"
          - "types-Jinja2"
          - "types-jsonschema"
